### PR TITLE
Reapp

### PR DESCRIPTION
**Pull request by natew**
Fixed tweenQueue

### CODE REVIEW

**Comment by natew** [comment]
For what it's worth, this won't work on es6 without adding a tweenQueue to the class constructor manually.

I ended up moving to react-animate, on a branch, so you could check there for ideas:

https://github.com/reapp/react.animate

**Comment by jide** [comment]
Interesting ! What branch is this ? :)

**Comment by jide** [comment]
Ah ok, got it.

**Comment by jide** [comment]
I've found animations using react.animate are much less performant than react-tween-state...

**Comment by jide** [comment]
Hum, sorry, that was my fault :/

**Comment by chenglou** [comment]
#26. Sorry about this, thanks again =).

**Pull request closed without merging**
