### PR TITLE
Remove react-dom peer dependency

### PR DESCRIPTION
**Pull request by magrinj**
This package is only use in example

### CODE REVIEW

**Comment by magrinj** [comment]
I'm not sure for the react package itself, but react-dom need to be remove

**Comment by sompylasar** [comment]
Any plans to merge this? Important for React 15 support ( #57 ).

**Comment by dfournier** [comment]
I think this should be merged quick or a lot of forks will be pushed on npm...

**Comment by Olliepop** [comment]
Until @chenglou merges this in you can change your package.json entry to
`"react-tween-state": "git@github.com:Olliepop/react-tween-state.git",`

Thanks @magrinj

**Comment by chenglou** [comment]
Thanks for the ping. Hard to keep up with the issues these days =].

Merged, pushed and published as 0.1.5.

**Pull request merged**
