### PR TITLE
Compatable with React classes. ...

### PR DESCRIPTION
**Pull request by natew**
Removes usage of this.setState and uses property instead. Tested as a decorator as well as a mixin with createClass on my own end.

### CODE REVIEW

**Comment by chenglou** [comment]
Did you try this on many components? If you mixin this in many you'll have a shared `tweenQueue` won't you?

**Comment by natew** [comment]
My update changed it so it sets it on componentWillMount. I think on es6 classes you'd need to set it up in your constructor though

**Comment by jide** [comment]
How would you use this without a decorator ?

**Comment by ponychicken** [comment]
Maybe you could update readme.md to demonstrate the new syntax

**Comment by chenglou** [comment]
Btw sorry for the late reply, but I'll pick this up eventually; the API's still changing so I don't want people having to re-port this to the class syntax all the time

**Comment by josebalius** [comment]
@chenglou is there a plan to merge this at some point or to support ES6 classes?

**Comment by chenglou** [comment]
Christ, sorry for the long wait.
@natew #30's shortcoming still applies here right? Needing to add tweenQueue manually?

**Comment by chenglou** [comment]
I'll be closing this following my explanation in #26. Thanks a lot!

**Pull request closed without merging**
